version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - wishlist-db:/data/db

  wishlist-api:
    container_name: wishlist-api
    image: wishlist-api:latest
    ports:
      - '8081:8080'
    environment:
      - MONGO_URL=mongodb
    depends_on:
      - mongodb

volumes:
  wishlist-db:
